/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief Hexagon fatal error handling
 */

#ifndef ZEPHYR_INCLUDE_ARCH_HEXAGON_ERROR_H_
#define ZEPHYR_INCLUDE_ARCH_HEXAGON_ERROR_H_

#include <zephyr/arch/exception.h>

#ifdef __cplusplus
extern "C" {
#endif

extern FUNC_NORETURN void z_hexagon_fatal_error(unsigned int reason);

#if defined(CONFIG_USERSPACE)

/*
 * z_hexagon_fatal_error() is a plain function call: calling it directly
 * from user mode would not just skip the user/kernel reason-filtering
 * that every other test in tests/kernel/mem_protect/userspace/ relies on
 * (a user thread forging K_ERR_KERNEL_PANIC, say, must be downgraded to
 * K_ERR_KERNEL_OOPS) -- it would also fault on its own, since it reads
 * G0-G3 directly (guest-privileged registers, see z_hexagon_get_current_esf())
 * and that read is itself a privilege violation from guest-user mode.
 * Route through a real syscall instead, exactly as arch_syscall_oops()
 * (userspace.c) already does for K_ERR_KERNEL_OOPS, so kernel-mode code
 * always sees a legitimate trap0 frame from hexagon_user_fault()'s z_impl_.
 *
 * Named hexagon_user_fault (not plain user_fault, RISC-V's name for the
 * same thing) because Zephyr's syscall list is generated by scanning
 * syscall-tagged declarations across every arch's headers, not just the
 * one being built for -- reusing RISC-V's name collides there even
 * though only one of the two headers is ever actually included in a
 * given build. XTENSA's xtensa_user_fault() sidesteps the same collision.
 */
__syscall void hexagon_user_fault(unsigned int reason);

/**
 * @brief Generate a software-induced fatal error.
 *
 * @param reason_p K_ERR_ scoped reason code for the fatal error.
 */
#define ARCH_EXCEPT(reason_p)				\
	do {						\
		if (k_is_user_context()) {		\
			hexagon_user_fault(reason_p);	\
		} else {				\
			z_hexagon_fatal_error(reason_p);	\
		}					\
		CODE_UNREACHABLE;			\
	} while (false)

#include <zephyr/syscalls/error.h>

#else /* !CONFIG_USERSPACE */

/**
 * @brief Generate a software-induced fatal error.
 *
 * @param reason_p K_ERR_ scoped reason code for the fatal error.
 */
#define ARCH_EXCEPT(reason_p)			\
	do {					\
		z_hexagon_fatal_error(reason_p);	\
		CODE_UNREACHABLE;		\
	} while (false)

#endif /* CONFIG_USERSPACE */

#ifdef __cplusplus
}
#endif

#endif /* ZEPHYR_INCLUDE_ARCH_HEXAGON_ERROR_H_ */
