#!/bin/bash
# Convert binary bitstream file to C header file for Zephyr

if [ $# -lt 1 ]; then
    echo "Usage: $0 <bitstream.bin> [output.h]"
    echo "Example: $0 blink.bin src/blink.h"
    exit 1
fi

INPUT_FILE="$1"
OUTPUT_FILE="${2:-src/blink.h}"

if [ ! -f "$INPUT_FILE" ]; then
    echo "Error: Input file '$INPUT_FILE' not found"
    exit 1
fi

# Get base name without extension and path
BASENAME=$(basename "$INPUT_FILE" .bin)
# Handle cases where basename might have underscores replaced with underscores
BASENAME_CLEAN=$(echo "$BASENAME" | sed 's/[^a-zA-Z0-9]/_/g')

# Convert to header file
xxd -i "$INPUT_FILE" > "$OUTPUT_FILE.tmp"

# Rename variables - keep as uint8_t since SPI uses 8-bit words
# Handle various naming patterns from xxd (filename_bin, filename_bin_len, etc.)
sed -i.bak \
    -e "s/unsigned char ${BASENAME_CLEAN}_bin\[\]/const uint8_t blink_bitstream[]/" \
    -e "s/unsigned char ${BASENAME}_bin\[\]/const uint8_t blink_bitstream[]/" \
    -e "s/unsigned int ${BASENAME_CLEAN}_bin_len/blink_bitstream_len/" \
    -e "s/unsigned int ${BASENAME}_bin_len/blink_bitstream_len/" \
    -e "1i\\
/*\\
 * Auto-generated from ${INPUT_FILE}\\
 * Generated by convert_bitstream.sh\\
 *\\
 * SPDX-License-Identifier: Apache-2.0\\
 */\\
\\
#include <stdint.h>\\
\\
" \
    "$OUTPUT_FILE.tmp"

# Remove backup file
rm -f "$OUTPUT_FILE.tmp.bak"

# Move to final location
mv "$OUTPUT_FILE.tmp" "$OUTPUT_FILE"

echo "Converted $INPUT_FILE to $OUTPUT_FILE"
echo ""
echo "Note: The array is declared as uint8_t (bytes) since SPI uses 8-bit words."
echo "The fpga_load() function will cast it appropriately."
