CONFIG_FPGA=y
CONFIG_SLG47910V_FPGA=y
CONFIG_SPI=y
CONFIG_PRINTK=y
CONFIG_CRC=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=4
# Increase stack size to handle large bitstream operations
CONFIG_MAIN_STACK_SIZE=4096
